# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  g: ./Taskfile.g.yml

tasks:

  ghq:
    dir: ~/bin
    desc: Install ghq (repo manager) to ~/bin
    cmds:
      - eget x-motemen/ghq
    
