# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  g: ./Taskfile.g.yml
  l: ./Taskfile.l.yml


tasks:

  container:
    desc: "Install all tools in container"
    cmds:
      - task: g:pinentry
      - task: g:git
      - task: g:lazy-git