# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:

  default:
    cmds:
      - which code
      - code --version
      - code --list-extensions
      - cmd: echo && echo
        silent: true

  set:
    desc: "Setup all available extensions"
    cmds:
      - task: set:bash
      - task: set:csv
      - task: set:git
      - task: set:golang
      - task: set:graphql
      - task: set:kube
      - task: set:ui
      - task: set:protobuf
      - task: set:yaml
      - task: set:vue
      - task: set:task

  delete:
    desc: "Delete all extensions"
    cmds:
      - code --list-extensions | xargs -L 1 code --uninstall-extension
