# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, World!

tasks:

  ready:
    desc: "Hide ready notifications"
    cmds:
      - gsettings set org.gnome.desktop.wm.preferences focus-new-windows 'smart'
